//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYsecondmvc.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email_id { get; set; }
        public string DOB { get; set; }
        public string Contact_No { get; set; }
        public string Address { get; set; }
    }
}
